id: A28EA452B
title: 'Vajrakīla Prayer: A Rain of Accomplishments'
type: translation
pechas:
- I4C14B237
- I4EAB742F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:59:23.336891
  last_modified_at: 2023-01-04 11:59:23.336907
  collections:
  - Gyarong Khandro Series
  - Works of Tibetan Masters
alignment_to_base:
  I4C14B237/4C73: '3928'
  I4EAB742F/195D: '3928'
